#!/bin/sh
#快捷结束进程 用法：kill9 关键字1 关键字2 关键字3

if [ -z "$1" ]; then

	echo "进程名称不能为空"
	exit

fi

name=$(ps -ef | grep "$1" | grep -v "kill9")


if [ "$2" ]; then

	name=$(echo "$name" | grep "$2")

fi


if [ "$3" ]; then

	name=$(echo "$name" | grep "$3")

fi

name=$(echo "$name" | grep -v "grep")

if [ -z "${name}" ]; then

    echo "未发现$1 $2 $3"

else

	pid=$(echo "$name" | awk '{print $2}')
    kill -9 ${pid}
    echo "发现进程信息："
	echo "$name"
	echo "已结束pid：${pid}"

fi
